chain_id = 245022939
operators_whitelist = [
    "2BLRSMH7RxoN26T2xmcj3krcWBMqA4E6F8j4T7nXep8Z",
    "2bFYfXNcumFtZWEEYB3pyMVTvkp4y3FsnTbGaFHAaSKy",
    "2daPxRAUscTaSXwpofVwbGt9SqfzrVnEnqZvYzCSP7BG",
    "3TjkdV6YEEqjSAmZU2PWAUGqzaC4GtPJGdMNUmqfJoQz",
    "4A9vUAziEma5HkpmqWzkZvband6mzX7KknnhnyG8xehb",
    "4a68HHvtQd3DQfnSUdRwiHphi2V61hburKvMHibQ3U6E",
    "4c3h5NrzSCYC94ZxjcMcxyKq2cxcWSBahZ4u1HLH3cZL",
    "4gmceVciF12xHPP1AJuDd5y5oTwHgxn9kGG4uoSxG21P",
    "52aVt6EgsriiwbxyM115Y8MiVPdjvwz9KdmAsjdrAm9o",
    "5Mw6mUFEuWuTDVsDbf2zsDzcspiwNkjZm92tXWPHJKou",
    "5ZwmwrbnJ4xm56Q4pXog3EVMDZ3sgzbrT1tBSTEXi4R6",
    "5dWQ96kagdnj2cLvR2EoSkxA7wFuUMp5deKyomQ5W5wb",
    "6XcDQz8WQdKrUpWkHfur8o6tWo5xJqYudSyYZ63AcbTC",
    "6ak9V4inZRf1sVo9Qev2bFwrAUJhfmKzbTei3kdBGRq8",
    "7JdqwYUupDxMcsxEmfDwfqHgL16Xk3KeTdTtHseJXHyP",
    "7gWnJ3VUJrhtXycMCdJU1jZ4aDqeuRy4u7h7CEwnrpZy",
    "7vAzji9q63T9fnCr6i3ftc6t9Nh48Bu8ouSn3tvY6We3",
    "81QTwdEsNNDZcEsweNvCHUuPkMRkW58A9B7aUhuXU1uw",
    "9TLsihHZckJTJse7giJeVNAJKP6GvmMW2N5dFGUeWcsj",
    "9XYgii3vQdds1LQPpA6XUtJXtKqtYtLsuLQPCHtpZoPS",
    "AeDUd2wnUugX9gMuoRm697Bnxtpx99kuMCj6wUu1mmUF",
    "B2TEb9ZPa6AbsStxYMFunXjhmP8xDVmj3nxLJZx1TvZv",
    "B4SV4cxkWXLk2s6z85ZJowpNX36hiyh91dnNQ6YD4RLM",
    "BJKbx3AUuQBpbQQEPxurNHY28Too4xSytHffRa53bByG",
    "BNjCSqrcoMfn3LUjYPsoY9eg67XeVoyj3qvQ5hDg4njm",
    "BP4gLptmyyViWKhQ3xuLuDntkmo3svyFi7fkUirJFeyD",
    "BPhWvbzBumUgYRBYFEQ276dJRQ8YYu25Woz1f7rChYg5",
    "BVRdXEfyUhkBpWPHBKRdrVMF7UayumC3vgCUwsa7qUVR",
    "BWNZMCu2EZAMqGX67upixqt95CUi2HjWY77MHFBj1tXN",
    "C1x4h51CM9LKCL4WSjcTCxBzLHYL39vMsPWxDdNvDeX3",
    "C2TS97ph8LECBUFk11KuVNvvfLDHexWiUXFKBnvxHqpf",
    "C5NL2wdFX27UAFWBzhJ5wmKwq49JEAbm9nsPaaXLNVuR",
    "C8wm8NHLsvNsa5M6fyBE6g5iMjyxcTqttxhk9u24cgt4",
    "CAx5h4RDMMNqsnuJKWM1uiPQhQXzLV3rq2qK6uJNSo59",
    "CBWmdUAtNA6iuM81eryVMf62XqXUkspN6LVftjScVGZL",
    "CfiwwqFAVcturqCcqisYuva2RHGPqvBaLMhSwqjCyGsb",
    "DJmAqnxJcVGDRvwnPnusxybk7b6GM3wsCvmbsZ8ZECgS",
    "DJoQr8oxdzGykVeNMDbDNbDvq4LLJymwE7wjzYBuJz5L",
    "DLMCYL14kZbfJi9L4hsTRLwMSjmvFmEL1vipnJWnvo88",
    "DtwjFJF4HAFx9krSe8QE5nQivkTvBuCC9q8Gwz66bYQy",
]

[token_mint]
neon_token_mint = "F9RL2GxXwncjWmzVcXcL7DiBmnmjAHtQxDjmDfY1ztJC"
decimals = 9
