
# Note: This crate must be built using cargo build-bpf

[package]
name = "evm-loader"
version = "0.7.6-dev"
description = "Neon EVM loader"
authors = ["NeonLabs Maintainers <maintainers@neonlabs.org>"]
edition = "2018"

[features]
alpha = []
mainnet = []
testnet = []
devnet = []
no-logs = []
no-entrypoint = []
test-bpf = []
custom-heap = []
default = ["custom-heap"]
tracing = ["evm/tracing", "evm-runtime/tracing", "solana-program-tracing"]

[dependencies]

solana-program = { version = "=1.9.12", default_features = false }
spl-token = { version = "3.2.0", default_features = false, features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.0.3", default_features = false, features = ["no-entrypoint"] }

solana-program-tracing = { version = "=1.9.12", path = "/home/user/CLionProjects/neonlabs/solana/sdk/program", default_features = false, package = "solana-program", optional = true }

num-derive = "0.3"
num-traits = "0.2"
thiserror = "1.0"
arrayref = "0.3.6"
hex = "0.4.2"
bs58 = "0.3.1"
ripemd160 = "0.9.1"
rlp = "0.5"
borsh = "0.9"
bincode = "1.3.3"

evm = { version = "0.18.0", path = "../rust-evm", default_features = false }
evm-runtime = { version = "0.18", path = "../rust-evm/runtime", default-features = false }

const_format = { version = "0.2.21" }
cfg-if = { version = "1.0" }
log = { version = "0.4", default-features = false }

#solana-sdk = "=1.9.12"
#solana-sdk = { version = "=1.9.12", path = "/home/user/CLionProjects/neonlabs/solana/sdk", default_features = false }
[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
